using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using PdfSharpCore.Drawing;
using PdfSharpCore.Pdf;
using TheArtOfDev.HtmlRenderer.PdfSharp;
namespace HTMLTOPDF.Models
{
    public static class DataStorage
    {
        
        public static List<Employee> GetAllEmployees() =>
            new List<Employee>
            {
                new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"},
                 new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"},
                 new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"},
                 new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"},
                 new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}, new Employee { NameRonak="Mike", LastName="Turner", Age=35, Gender="Male"},
                new Employee { NameRonak="Sonja", LastName="Markus", Age=22, Gender="Female"},
                new Employee { NameRonak="Luck", LastName="Martins", Age=40, Gender="Male"},
                new Employee { NameRonak="Sofia", LastName="Packner", Age=30, Gender="Female"},
                new Employee { NameRonak="John", LastName="Doe", Age=45, Gender="Male"}
            };
    }
}
